config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index', as: :home

  get '/index' => 'users#index'

  get '/search' => 'home#search'

  get 'signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/users/:id/posts' => 'users#posts', as: :user_posts

  resources :users

  resources :posts do
    resources :comments
  end

end

app/models/add_columns_to_user.rb
class AddColumnsToUsers < ActiveRecord::Base
	add_column :users, :age, :integer
	add_column :users, :city, :string
	add_column :users, :country, :string
	add_column :users, :gender, :string
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_attached_file :avatar, :styles =>
	{ :medium => "300x300>", :thumb => "100x100>"},
	:default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar,
	:content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_attached_file :avatar, :styles =>
	{ :medium => "300x300>", :thumb => "100x100>"},
	:default_url => "/images/mymic.jpg"
	validates_attachment_content_type :avatar,
	:content_type => /\Aimage\/.*\Z/

	validates :email, presence: true
	validates :password, confirmation: true, presence: true
	validates :gender, inclusion: {in: ["male", "female"]}
	validates :username, presence: true, uniqueness: { message: "username is already in use"}

	before_validation :regulate_name, on: :create
 
 
	def regulate_name
	    self.fname = self.fname.downcase.titleize
	    self.lname = self.lname.downcase.titleize
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		@comment.post_id = params[:post_id]
		@comment.user = current_user
		@comment.save
		redirect_to post_path params[:post_id]
	end

	def destroy
		@comment = Comment.find( params[:id])
		@comment.destroy
		render json: { message: 'Success!' }
	end	


	private

	def comment_params
		params.require(:comment).permit(:comment)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def show
		@post = Post.find_by_id params[:id]
		@comment = Comment.new
	end

	def index
		@posts = Post.all.order(id: :desc)
	end

	def create
		@post = Post.new post_params
		@post.user = current_user
		@post.save # add flash
		# redirect_to user_path current_user
		respond_to do |format|
			format.js do
				render 'show'
			end
			format.html do 
				redirect_to current_user
			end
		end
	end

	private
	def post_params
		params.require(:post).permit(:title, :subject, :body, :avatar)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		puts "MY PARAMS"
		pp params
		@user=User.where(username: params[:session][:username]).first
		if @user && @user.password == params[:session][:password]
			flash[:notice] = "You're in!"
			session[:user_id] = @user.id
			redirect_to user_path @user	
		else
			flash[:alert] = "There seems to be a problem, try again."
			redirect_to users_path
		end
	end

	def destroy
		session.delete :user_id
		redirect_to '/index'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end
	def show
		@user = User.find params[:id]
		@post = Post.new
		@top_three_posts = @user.posts.order(id: :desc).limit 3
	end

	def posts
		@user = User.find params[:id]
		@posts = @user.posts.order(id: :desc)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Account Created!"
			redirect_to '/index'
		else
			flash.now[:alert] = "There was a problem creating your account"
			render :new
		end
	end
	
	def destroy
		@user = User.find params[:id]
		@user.destroy
		redirect_to '/index'
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		if @user.update_attributes user_params
			flash[:notice] = "Got it now!"
			redirect_to '/users'
		else
			flash[:alert] = "Something's wrong... Try again."
			redirect_to edit_user_path @user
		end
	end

	private
	def user_params
		params.require(:user).permit(:fname, :lname, :gender, :age, :email, :city, :country, :avatar, :username, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end

end

app/views/home/index.html.erb
<h1>
	Welcome to My New Example!
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="style.css.erb">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<center><h3>
<nav>
<!-- need reminder on how to properly reference the paths/views in the navigator below -->
	<ul id="nav">
	<%if current_user %>
		<li>
			<%= link_to "Home", home_path %> | 
		</li>
		<li>
			<%= link_to "Profile", user_path(User.find_by_id(current_user.id)) %> | 
		</li>
		<li>
 			<%= link_to current_user.fname + "'s Posts", user_posts_path(current_user.id) %> |
		</li>
		<li>
			<%= link_to "Postfeed", posts_path %> | 
		</li>
		<li>
			<%= link_to "Account", edit_user_path(current_user.id) %> | 
		</li>
		<li>
			<%= link_to "Sign Out", logout_path, method: :delete %>
		</li>

	<% end %>		
	</ul>
</nav>
<div id="spinner">
	<img src="/images/35.jpg">
</div>
	<h1>
		Welcome Animal Lovers!
	</h1>
<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>
<%= yield %>
</h3></center>
</body>
</html>

app/views/posts/_post.html.erb
		<%= image_tag @post.avatar.url(:medium) %>
	<h3>
		Title: <%= @post.title %>
		<br>
		by: <%= @post.user.fname %>
	</h3>
		Subject: <%= @post.subject %>
		<br>
		<%= @post.body %>

app/views/posts/index.html.erb
	<h2>
		Here's What Everyone Is Talking About:
	</h2>
	
	<% @posts.each do |post| %>
	<h3>
		<%= link_to post.title, post %><br>
		By: <%= post.user.fname %>
	</h3>
		Subject: <%= post.subject %>
	<h3><u>
		Comments:
	</u></h3>
		<% post.comments.each do |comment| %>
		<%= comment.user.fname %>
		<br>
		<%= comment.comment %>
		<br><br>
	<% end %>
	<% end %>

app/views/posts/show.html.erb
	
<%= render @post %>
	<br><br>
		<%= form_for @comment, url: post_comments_path(@post) do |f| %>
		<%= f.label :comment, 'Comment' %><br>
		<%= f.text_field :comment %><br>
		<br>
		<%= f.submit 'Post Comment' %>
	<h3><u>
		Comments:
	</u></h3>
		<% @post.comments.each do |comment| %>
		<div>
		<%= comment.user.fname %>
		<br>
		<%= comment.comment %>
		<br>
		<%= link_to "Delete Comment", post_comment_path(@post.id, comment.id), method: :delete, remote: true, class:  "delete-comment" %>
		</div>
		<br><br>
	<% end %>
		<% end %>

app/views/posts/show.js.erb
// alert('Your post was saved');
// $('#new_post').html('<h1>Post Saved!</h1>');
$('#new_post').html("<%= escape_javascript render @post %>");

app/views/users/edit.html.erb
<h1>
	Edit User
</h1>

	<div id="signup">
	<%= image_tag @user.avatar.url(:medium) %>
		<%= form_for @user, method: :put do |f| %>
		<%= f.label :username, 'Username' %><br>
		<%= f.text_field :username %><br>
		<%= f.label :password, 'Password' %><br>
		<%= f.text_field :password %><br>
		<%= f.label :fname, 'First Name' %><br>
		<%= f.text_field :fname %><br>
		<%= f.label :lname, 'Last Name' %><br>
		<%= f.text_field :lname %><br>
		<%= f.label :gender, 'Gender' %><br>
		<%= f.text_field :gender %><br>
		<%= f.label :age, 'Age' %><br>
		<%= f.text_field :age %><br>
		<%= f.label :email, 'Email' %><br>
		<%= f.text_field :email %><br>
		<%= f.label :city, 'City' %><br>
		<%= f.text_field :city %><br>
		<%= f.label :country, 'Country' %><br>
		<%= f.text_field :country %><br>
		<br>
		<%= f.submit 'Update' %>
		<% end %>
		<br><br><br><br>
		<%= form_for @user, method: :delete do |f| %>
		<%= f.submit 'Delete Account' %>
		<% end %>
		
	</div>

app/views/users/index.html.erb
<center>
	<% if current_user %>

		<div>
			<% @users.each do |user| %>
		</div>
			<div>
				<%= link_to user.fname + " " + user.lname, user %>
			</div>
		<div>	
			<% end %>
		</div>
	
	<% else %>
<p id="signup">
	Need an Account? <%= link_to "Sign Up!", signup_path %> 
</p>
		<div id="login">
			<%= form_for :session, url: login_path do |f| %>
			<%= f.label :username, 'Username' %><br>
			<%= f.text_field :username %><br>

			<%= f.label :password, 'Password' %><br>
			<%= f.password_field :password %><br>
			<br>
			<%= f.submit 'Log In' %>

			<% end %>	
		</div>
	<% end %>
</center>

app/views/users/new.html.erb
<center>

<h2>
	Sign Up!
</h2>

	<div id="signup">
	<% @user.errors.full_messages.each do |message| %>
		<%= message %>
	<% end %>
		<%= form_for @user, :html => { :multipart => true } do |f| %>
		<%= f.label :username, 'Username' %><br>
		<%= f.text_field :username %><br>
		<%= f.label :password, 'Password' %><br>
		<%= f.password_field :password %><br>
		<%= f.label :password_confirmation, 'Password Confirmation' %><br>
		<%= f.password_field :password_confirmation %><br>
		<%= f.label :fname, 'First Name' %><br>
		<%= f.text_field :fname %><br>
		<%= f.label :lname, 'Last Name' %><br>
		<%= f.text_field :lname %><br>
		<%= f.label :gender, 'Gender' %><br>
		<%= f.text_field :gender %><br>
		<%= f.label :age, 'Age' %><br>
		<%= f.text_field :age %><br>
		<%= f.label :email, 'Email' %><br>
		<%= f.text_field :email %><br>
		<%= f.label :city, 'City' %><br>
		<%= f.text_field :city %><br>
		<%= f.label :country, 'Country' %><br>
		<%= f.text_field :country %><br><br>
		<%= f.file_field :avatar %>

		<br>
		<%= f.submit 'Create' %>

		<% end %>	
	</div>

</center>

app/views/users/posts.html.erb
	<h2>
		<%= @user.fname %>'s Awesome Posts:
	</h2>
	
	<% @posts.each do |post| %>
	<h3>
		<%= link_to post.title, post %>
	</h3>
		Subject: <%= post.subject %>

	<% end %>

app/views/users/show.html.erb
<center>

	<%= image_tag @user.avatar.url(:medium) %>
		<%= form_for @post, url: posts_path, html:{mulitpart: true} do |f| %>
		<%= f.label :title, 'Title' %><br>
		<%= f.text_field :title %><br>
		<%= f.label :subject, 'Subject' %><br>
		<%= f.text_field :subject %><br>
		<%= f.label :body, 'Your Message' %><br>
		<%= f.text_field :body %><br>
		<%= f.file_field :avatar %>
		<br>
		<%= f.submit 'Post' %>
		<% end %>
	<h2>
		<%= @user.fname %> has a sweet profile. Check it out:
	</h2>
	<h3>
		Name: <%= @user.fname + " " + @user.lname %>
		<br>
		Age: <%= @user.age %>
		<br>
		Gender: <%= @user.gender %>
		<br>
		City: <%= @user.city %>
		<br>
		Country: <%= @user.country %>
		<br>
		Username: <%= @user.username %>
		<br>
		Email: <%= @user.email %>
		<br>
	</h3>
	<h2>
		<%= @user.fname %>'s Awesome Posts:
	</h2>
	
	<% @top_three_posts.each do |post| %>
	<h3>
		<%= link_to post.title, post %>
	</h3>
		Subject: <%= post.subject %><br>
		<br><br>
	<% end %>
	
</center>